# Create new conda environment (named "hwobows") simply by running:
#   conda env create -f environment.yml
name: hwobows
dependencies:
  - conda-forge::numpy
  - conda-forge::pip
  - conda-forge::python==3.10  # Python 3.11 seems to break snakemake?
  - pip:
      - matplotlib==3.7
      - pandas
      - astropy
      - scipy
      - tqdm
